[package]
name = "dapr"
version = "0.10.0"
authors = ["dapr.io"]
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/dapr/rust-sdk"
description = "Rust SDK for dapr"
readme = "README.md"
keywords = ["microservices", "dapr"]


[dependencies]
tonic = "0.5"
prost = "0.8"
bytes = "1"
prost-types = "0.8"
async-trait = "0.1"
serde = {version = "1.0.152", features = ["derive"], optional = true}
serde_json = {version = "1.0.91", optional = true }
proc_macros = {path = "./proc-macros", optional = true}

[workspace]
members = ["proc-macros"]

[features]
serde = ["dep:serde", "dep:serde_json"]
proc-macros = ["dep:proc_macros"]
full = ["serde", "proc-macros"]

[build-dependencies]
tonic-build = "0.5"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "client"
path = "examples/client/client.rs"

[[example]]
name = "publisher"
path = "examples/pubsub/publisher.rs"

[[example]]
name = "subscriber"
path = "examples/pubsub/subscriber.rs"
